config/routes.rb
Samplaapp::Application.routes.draw do
   resources :users #this is used to retrieve the URL for user and their id(ex:  /users/1)
   resources :sessions, only: [:new, :create, :destroy] # we did this "only" option, Since we have no need to show or edit sessions, we’ve restricted the actions to new, create, and destroy using the :only option accepted by resources.

   root 'static_pages#home' # by making the home root , we will see the home page when we run 'http://localhost:3000/'
   match '/signup', to: 'users#new', via: 'get'
   match '/signin',  to: 'sessions#new', via: 'get'
   match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
 

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact Us</h1>
<p>Ruby on Rails Tutorial Sample App chapeter3
	<a href="http://ruby.railstutorial.org/chapters/static-pages#top"></a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>help me</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
</p>

app/views/static_pages/home.html.erb

<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>

	<h2>
		This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</h2>

<%= link_to "sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt:"Rails"), 'http://rubyonrails.org/'%>