config/routes.rb
Samplaapp::Application.routes.draw do
   resources :users #this is used to retrieve the URL for user and their id(ex:  /users/1)
   resources :sessions, only: [:new, :create, :destroy] # we did this "only" option, Since we have no need to show or edit sessions, we’ve restricted the actions to new, create, and destroy using the :only option accepted by resources.

   root 'static_pages#home' # by making the home root , we will see the home page when we run 'http://localhost:3000/'
   match '/signup', to: 'users#new', via: 'get'
   match '/signin',  to: 'sessions#new', via: 'get'
   match '/signout',  to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
 

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by AL Toukara
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>


app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "sample app", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home",   root_path %></li>
					    <li><%= link_to "Help",   help_path %></li>

					    <!-- The way to change the links in the site layout involves using an if-else branching structure inside of Embedded Ruby like this:
					      if signed_in? 
					      # Links for signed-in users
					      else
					     end

					    but completing it, the test in spec/requests/authentication_pages_spec.rb m for describe "with valid information" will pass.
					    we used  the boostrap which you can take a look at http://getbootstrap.com/.
					    but The dropdown menu requires the use of Bootstrap’s JavaScript library, which we can include using the Rails asset pipeline by editing the application JavaScript file in app/assets/javascripts/application.js add this line //= require bootstrap
					    -->


					    <% if signed_in? %>
           				   <li><%= link_to "Users", '#' %></li>
            			   <li id="fat-menu" class="dropdown">
             				    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               					  Account <b class="caret"></b>
              				    </a>
              					<ul class="dropdown-menu">
               						<li><%= link_to "Profile", current_user %></li>
                					<li><%= link_to "Settings", '#' %></li>
               					    <li class="divider"></li>
                					<li>
                 					  <%= link_to "Sign out", signout_path, method: "delete" %>
                					</li>

				        		    <!-- look in config/routes.rb for signout path . Notice that the signout link passes a hash argument indicating that it should submit with an HTTP DELETE request -->
				        		</ul>
				        	</li>
				        <% else %>
           					<li><%= link_to "Sign in", signin_path %></li>

				       		<!-- we could write
				       		user_path(current_user) instead of signin_path
				       		but Rails allows us to link directly to the user, in this context automatically converting current_user into user_path(current_user) --> 
				        <% end %>
				    </ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title> <!--app/helpers/application_helper.rb -->
  <%= stylesheet_link_tag    "application", media: "all", 
  "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container">
    <!--a message that appears on the subsequent page (in this case, welcoming our new user to the #application) and then disappears upon visiting a second page or on page reload
    # see app/controllers/users_controller.rb  to make your own flash message-->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

		<%= yield %>
        <%= render 'layouts/footer' %>
        #this line on the bottom just shows some useful infos about your webpages
        <%= debug(params) if Rails.env.development? %> 

	</div>
</body>
</html>